### ISSUE TITLE
Fix Javascript applet on Block25 page

### ISSUE THREAD

**Issue by lfuelling** [gtasa-savegame-editor/docs#5]
The javascript converter applet on [Block25](https://gtasa-savegame-editor.github.io/docs/#/block25) is currently non functional. No documentation for this exists except what @paul35621 wrote me:

> I think it simply did 6 + 6n and then converts to hexadecimal, so you can easily find the offset of a teleport in a block.

**Comment by nicolaisueper** [comment]
Closed with merge of #10

**Comment by lfuelling** [comment]
Unfortunately it doesn't work. The question is: is it because deployments using Travis CI are buggy/broken or caching (did a hard reload, still doesn't work) or is it just a :bug: ... :thinking:

**Comment by lfuelling** [comment]
Okay, I checked everything it seems like Travis is broken :roll_eyes:
